version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  my_dbdata:
