version: "3"

services:
  database:
    image: postgres:latest
    environment:
      PGDATA: /tmp
      POSTGRES_DB: "tutoring"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  minio:
    hostname: minio
    container_name: minio
    image: minio/minio
    command: server /export
    ports:
      - "9000:9000"
    restart: always
    environment:
      MINIO_ACCESS_KEY: 4D9185C8CC9649B9
      MINIO_SECRET_KEY: 162865EFD4DC4D1DB4F6A3D05559F54C
    volumes:
      - minio-data:/export

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - /backend/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  my_dbdata:
  minio-data:
